### ISSUE TITLE
Tracker shows "Rank complete" before the end

### ISSUE THREAD

**Issue by Orphis** [zephyron1237/adcom-mission-tracker#1]
With the current event, I am at level 20 + 7/9 objectives complete.
Adding another objective should show 8/9 but instead, I get "Rank complete".

**Comment by zephyron1237** [comment]
I really appreciate you reaching out to me about these two huge bugs around the end of events.  I'm surprised nobody else has brought this up, but I'm sure everybody's who's getting to rank 21 will appreciate it, too!  Should be fixed as of 6076f70
