### ISSUE TITLE
Enter multipliers by researcher level rather than raw number

### ISSUE THREAD

**Issue by thestorm042** [zephyron1237/adcom-mission-tracker#12]
Since the events sometimes have screwy multipliers, it's easier to just say what level the relevant researchers are.

This will require a bit of effort and UI updates to account for rare/epic/supreme, but since those don't change too often, it may still be convenient to use.

**Comment by zephyron1237** [comment]
As of Version 7.0, this feature should now be implemented.  This took "a bit of effort" :) da5d0c7
