### ISSUE TITLE
Display purchase costs on mouseover

### ISSUE THREAD

**Issue by thestorm042** [zephyron1237/adcom-mission-tracker#13]
In the mission calculator, when you mouseover a unit name/icon, it should display a tooltip showing how much it costs to purchase.  This will prevent many frequently asked questions in the Discord.

Ideally, it should also show the production value and time (either raw values or adjusted based on information already entered by the user to account for rares, etc.

**Comment by zephyron1237** [comment]
Instead of doing it strictly on mouseover, Version 7 has a detailed popover when you click the generator's icon in the Generators tab.  Hopefully this meets your needs.  Commit: da5d0c7
