### ISSUE TITLE
Off-by-one error in Rank selection?

### ISSUE THREAD

**Issue by mechpaul** [zephyron1237/adcom-mission-tracker#15]
https://github.com/zephyron1237/adcom-mission-tracker/blob/87d817d85648d80819cb87d14922662083eaa4c2/missions.js#L394

Reproduce the issue:
1. Go to Zephyron main page for motherland event: https://zephyron1237.github.io/adcom-mission-tracker/
2. Select the "#" button to jump to a specific rank
3. Enter "95"
4. An error is thrown: "Invalid rank: 95"

Expected result:
Rank 95 should be a valid rank.

**Comment by PhilippNowak96** [comment]
Rank 95 has currently no missions. I'm not sure if you even can level up after 94 but if you can do so there will be no missions.

**Comment by zephyron1237** [comment]
@mechpaul Thank you very much for submitting this issue that I was unaware of, and providing a detailed repro report.  This should be fixed on live as of my current commit: 5ce92e1

@PhilippNowak96 Rank 95 does indeed have missions currently.  You can see them on the [tracker](https://zephyron1237.github.io/adcom-mission-tracker/?rank=95) or [wiki](https://adventurecommunist.fandom.com/wiki/Rank_95).
