### ISSUE TITLE
I imagine this probably wasn't intended.

### ISSUE THREAD

**Issue by The-Snide-Sniper** [zephyron1237/adcom-mission-tracker#17]
![IMG_0185](https://user-images.githubusercontent.com/19253237/72991162-0f1ba180-3db7-11ea-9bad-100b3a1b7d32.jpeg)

NaN undefined per second is probably a bug I would think.

It mainly seems to happen when I set researcher levels.

**Comment by zephyron1237** [comment]
@The-Snide-Sniper This is the second report I've seen of this, but I've been struggling to reproduce this on my end.  Somewhere in the 🔨Power derivation calculations it's not finding a number.  Is there any further info you could provide to help me narrow this down?  Ideally, could you figure out a set of steps that guarantees that you go from not seeing the error to seeing the error?  If not, even some information like what browser you're using might help-- I think the one other instance I've seen of this was on an iPhone so if you're also on safari maybe that's related?

**Comment by The-Snide-Sniper** [comment]
Did ya one better and managed to find the exact line that was causing the problem.

**Comment by zephyron1237** [comment]
Fixed with The-Snide-Sniper's very own PR #20 .  Thanks for being such a big help!
