### ISSUE TITLE
Pressing "import counts" from the researcher screen resets all generator counts to zero

### ISSUE THREAD

**Issue by DefaultRyan** [zephyron1237/adcom-mission-tracker#19]

**Comment by zephyron1237** [comment]
@DefaultRyan Thanks for this bug report.  Is it possible this bug may actually be a similar known bug where changing any value on the Researcher or Trades tabs (e.g., leveling up a researcher, or typing in a new "next trade cost") recreates all the other tabs from scratch, which wipes out all "unsaved" information?

In my limited testing, I always see correctly imported Generators if I do variants of the following (as long as I don't touch researchers or trades)
1. Create import data (Open a popup, type in generators, click calculate)
2. Click over to the Researchers tab, then click "import data," then click back to the Generators tab.

**Comment by zephyron1237** [comment]
@DefaultRyan I have fixed the bug I mentioned in my previous response (as of 3c6e3fe), so hopefully that specific issue should stop causing generator counts to be reset.

Are you still having issues with the Import button, as I have not been able to reproduce this or seen any reports?

**Comment by DefaultRyan** [comment]
I think that fixed the issue. Thanks!
