### ISSUE TITLE
Cannot complete objectives for last rank in event mode

### ISSUE THREAD

**Issue by Orphis** [zephyron1237/adcom-mission-tracker#2]
With the current event, clicking on the objectives in the last category doesn't do anything. It should mark them as complete to help keeping track on what is coming next.

**Comment by zephyron1237** [comment]
I really appreciate you reaching out to me about these two huge bugs around the end of events.  I'm surprised nobody else has brought this up, but I'm sure everybody's who's getting to rank 21 will appreciate it, too!  Should be fixed as of 6076f70
