### ISSUE TITLE
Rounding errors in crit chance

### ISSUE THREAD

**Issue by The-Snide-Sniper** [zephyron1237/adcom-mission-tracker#21]
![IMG_0186](https://user-images.githubusercontent.com/19253237/73027472-16639f00-3df9-11ea-9cb0-94f52fa323dc.jpeg)
I was playing with the generator descriptions and found this stuff. Seems to only happen with maxed Shortstack and crit chance researchers, which nobody will ever get, but it would be pretty easy to fix I imagine.

**Comment by zephyron1237** [comment]
Yeah it's on my internal todo list on discord (which I should probably just do as actual issues since people are actively using the issue tracker now), and already fixed locally.  Hopefully I should get the change out with a few fixes including this one in a few hours.

**Comment by zephyron1237** [comment]
Should be fixed on live as of 73684c1

Thanks again for your reports and your PR :)
