### ISSUE TITLE
CPS for the current event includes previous CPS

### ISSUE THREAD

**Issue by EdricChan03** [zephyron1237/adcom-mission-tracker#25]
Currently, in the "Trades" tab of the "All Industries" dialog, there's a CPS text that indicates the current **C**omrades **p**er **S**econd.

However, as of right now, the CPS also includes the CPS from the Winter Event. See the screenshot below:

![Screenshot of "Trades" tab in "All Industries" dialog](https://user-images.githubusercontent.com/20047125/73537298-19970480-4463-11ea-9dff-23b1ba34147e.jpg)

**Comment by zephyron1237** [comment]
Thanks again for the report.  This should now be fixed as of d0236c3
