### ISSUE TITLE
Use React for UI rendering

### ISSUE THREAD

**Issue by edvinerikson** [zephyron1237/adcom-mission-tracker#26]
I would like to know if there would be any interest in moving from jQuery to React. If there is interest in that I would like to add the infra/foundation for that. 

I have two proposals that we can do here.

1. Add a build system and get code bundling and all that (use create-react-app / nextjs). 
   The benefits of this is that we get service-worker support, web manifest, JSX syntax, and will probably scale better. However the downside is that you would need to install the nodejs and npm tool chain in order to work on the tracker.
2. Don't add a build system and use React the same way you use jQuery today (from globals on the window object).
  Benefits here is that it's quite simple and does not introduce any significant changes to the app. Most of the steps you do today will still be the same, with the exception that you build React components instead of jquery/templating. This comes with the downside of a less ideal developer experience and scalability. 

Note that none of the proposals involve re-writing anything. That can be done incrementally.

**Comment by zephyron1237** [comment]
> The benefits of this is that we get service-worker support, web manifest

Please excuse my knowledge of service workers and web manifests, as it is very limited, but I was under the impression they were both built-in features of browsers and could be immediately added to my current structure.  What would a build system add to those?

**Comment by edvinerikson** [comment]
Yeah you could have them without build systems too. However, create-react-app comes with that added by default.
