### ISSUE TITLE
Base displayed strings on Localization, not Balance

### ISSUE THREAD

**Issue by zephyron1237** [zephyron1237/adcom-mission-tracker#29]
The Balance data contained in `data.js` has names for everything, but these are not actually ever used in-game, so they can contain some errors and inconsistencies (like capitalization) that make the tracker less polished and occasionally confusing.

This issue is for the task of:
1. Adding the localization config to `data.js` (or elsewhere if it makes more sense).  This isn't as trivial as adding a balance config to `data.js` since the localization config is not formatted as a javascript object, but just lines of key.subkey.subsubkey=value.  My instinct would be to add it as a string at the end of `data.js`.  The best solution would probably be for everything in `data.js` to be in their own files, but AFAIK that prevents testing without setting up a local webhost.
2. Change all the display names to be based on the localization data.  This is probably easy, since I think I tried to quarantine these to specific functions like `resourceName()`, but I didn't do this for researchers, so you'll need to search for `.Name` and replace those with a new function.

Attached is the [current Localization file](https://github.com/zephyron1237/adcom-mission-tracker/files/4220792/Localization.English.json.zip) if somebody besides me wants to take a shot at this.  If you need a newer version, let me know and I'll be happy to show you how to get your own copies.

**Comment by The-Snide-Sniper** [comment]
You can easily turn that all into JSON like so:

    const raw = /* put the string here */;
    function getJSON(data) {
        let lines = data.split('\n');
        let root = {};
        for (let line of lines) {
            let sides = line.match(/(.*?)=(.*)/);
            root[sides[1]] = sides[2];
        }
        return JSON.stringify(root);
    }
You can then put it in data.js.

**Comment by zephyron1237** [comment]
This has been implemented as of f9644b3
