### ISSUE TITLE
Edge support - Error in JS file

### ISSUE THREAD

**Issue by mechpaul** [zephyron1237/adcom-mission-tracker#3]
I'm trying to run the webpage https://zephyron1237.github.io/adcom-mission-tracker/?rank=event# from Edge. It throws the following exception:

SCRIPT1028: SCRIPT1028: Expected identifier, string or number
missions.js (1226,25)

which is the line:

let combinedValues = {...industryValues, ...globalValues};

I'm betting it doesn't like the … values. Could you have a look?

Because of this error, the page renders with no dynamic content (only HTML/CSS render)

**Comment by zephyron1237** [comment]
Thank you very much for this detailed report.  I am surprised no other Edge users have mentioned this yet.  You are correct that Edge does not yet support that notation (the object version of the spread syntax).  I rewrote that section to be more compatible, and this issue should be fixed as of 0eebdda .
