### ISSUE TITLE
Incorrect mission values for Impressive Infrastructure event

### ISSUE THREAD

**Issue by DefaultRyan** [zephyron1237/adcom-mission-tracker#41]
For rank 6:
- The tracker showed "Own Papyruses 456,000", but the actual mission was 500,000.
- Tracker showed "Own Calendars (42)", but the actual mission was 62.

**Comment by DefaultRyan** [comment]
Another one:
- Own calendars (28,288) but game shows 23,233

**Comment by zephyron1237** [comment]
Thanks for the report @DefaultRyan .  The issue is that Ages 1.13 and 1.14 have different balances for Infrastructure, and both versions are live (since 1.14 is out but not forced yet).  The Tracker cannot handle two balances at once, so the data from 1.14 is being shown.
