### ISSUE TITLE
New offline calculator is broken, causing website hangs

### ISSUE THREAD

**Issue by DefaultRyan** [zephyron1237/adcom-mission-tracker#44]
Should probably try to revert #43 while investigating.

I'm using a mission in the current (music) event.

In Rank 18, there is a mission "Own Microphones (5)", and I've entered the following values:
Generators:
- Drum Kits 6.55 kk
- Saxophones 1.71 gg
- Keyboards 1.9 cc
- Electric Guitars 3.79 b
- Microphones 2
- Music stands 3.59 oo

Heroes levels:
- Level 7
- Level 7
- Level 6
- Level 6
- Level 3
- Level 4
- Active

Upgrades (probably shouldn't matter):
- 5 tt
- 5 oo
- 5 jj
- 50 aa
- Level 4
- Level 4
- Level 4
- Level 0

The regular (non-offline calculation runs fine), returning 9h 24m 04s. But the offline calculator appears to hang indefinitely.

**Comment by DefaultRyan** [comment]
Perhaps @darrenrs could look into testing this case.

**Comment by darrenrs** [comment]
Was just missing a specific check for "Own" generator missions vs. "Collect" resources missions. Thanks for letting us know.

**Comment by DefaultRyan** [comment]
It's not hanging, but it's returning wildly incorrect results. The same test case I outlined is still retuning 9+ hours for the basic case, but the offline case is returning 1s, which can't possibly be correct.

**Comment by zephyron1237** [comment]
Is this still happening? Hanging was fixed as of 28ffaaf and the incorrect answers should now be fixed as of b3e8632 (pushed a few minutes ago)

**Comment by darrenrs** [comment]
It's working on multiple users' ends now—clearing your cache should fix it for good.

**Comment by DefaultRyan** [comment]
All good now. Thanks!

**Comment by zephyron1237** [comment]
What values are you using for this test?  I used the values you provided in your original message (except for music stands, which I left blank) on the 3.53 OO mission.  My results were

No Options (Online): 1h 58m 54s
Offline: 1h 46m 52s

Which seems reasonable.

**Comment by DefaultRyan** [comment]
Performing another refresh cleared things up. Thanks.
